spring:
  datasource:
    url: ${ORACLE_DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  server-url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}