spring:
  datasource:
    url: ${ORACLE_DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  server-url: ${SWAGGER_SERVER}


cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}